### PR TITLE
Fix #56: Container exited with status code 1, but don't show errors.

### LINKED ISSUE #56: Container exited with status code 1, but don't show errors
# How to reproduce?
## Files 
```Dockerfile
# Dockerfile
FROM python:3.6-alpine

ENTRYPOINT ["python"]
CMD ["-c", "print(a)"]
```
```go
//main.go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/nuveo/gofn"
	"github.com/nuveo/gofn/provision"
)

func main() {
	buildOpts := &provision.BuildOptions{
		ImageName:               "docker_test",
		DoNotUsePrefixImageName: true,
	}
	stdout, stderr, err := gofn.Run(buildOpts, nil)
	if err != nil {
		log.Println(err)
		os.Exit(1)
	}
	fmt.Println("Stderr: ", stderr)
	fmt.Println("Stdout: ", stdout)
	os.Exit(0)
}

```

## steps

Build the image `docker build -t docker_test`

Run `go run main.go`

## expected behavior

print log with error and exit with status 1

## actual behavior

don't have error, print stderr(with traceback) and exit with 0

### PR DESCRIPTION
**Pull request by cassiobotaro**
- verify if container exited with 0
- change variable name to avoid conflict

### CODE REVIEW

File: provision/docker.go [hunk 1]
```diff
@@ -211,15 +214,18 @@ func FnLogs(client *docker.Client, containerID string, stdout io.Writer, stderr
...
+	errs := make(chan error)
 	go func() {
-		_, err := client.WaitContainer(containerID)
+		code, err := client.WaitContainer(containerID)
 		if err != nil {
-			errors <- err
+			errs <- err
+		}
+		if code != 0 {
+			errs <- ErrContainerExecutionFailed
```
Comment (felipeweb) [inline provision/docker.go]: Is it possible to get why do not exited with 0?

Comment (cassiobotaro) [inline provision/docker.go]: it's necessary?

Comment (felipeweb) [inline provision/docker.go]: no, because it's in stderr
