### PR TITLE
caught logs when execution failed

### LINKED ISSUE #58: When execution failed, logs are not captured
# How to reproduce?
## Files 
```Dockerfile
# Dockerfile
FROM python:3.6-alpine

ENTRYPOINT ["python"]
CMD ["-c", "print(a)"]
```
```go
//main.go
package main

import (
	"fmt"
	"log"
	"os"

	"github.com/nuveo/gofn"
	"github.com/nuveo/gofn/provision"
)

func main() {
	buildOpts := &provision.BuildOptions{
		ImageName:               "docker_test",
		DoNotUsePrefixImageName: true,
	}
	stdout, stderr, err := gofn.Run(buildOpts, nil)
	if err != nil {
                fmt.Println("Stderr: ", stderr)
	        fmt.Println("Stdout: ", stdout)
		log.Println(err)
		os.Exit(1)
	}
	fmt.Println("Stderr: ", stderr)
	fmt.Println("Stdout: ", stdout)
	os.Exit(0)
}

```

## steps

Build the image `docker build -t docker_test`

Run `go run main.go`

## expected behavior

some output in stdout or error

## actual behavior

stdout and stderr are empty

### PR DESCRIPTION
**Pull request by cassiobotaro**
Will fix #58

### CODE REVIEW

File: examples/running_log/main.go [hunk 1]
```diff
@@ -15,12 +15,7 @@ func main() {
 	if err != nil {
 		log.Fatal(err)
 	}
-	defer func() {
```
Comment (avelino) [inline examples/running_log/main.go]: View this doesn't seem right. Nor has it is necessary to test, lint is good practice
